# Generated by Django 5.2.5 on 2026-06-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='mood',
        ),
    ]
