# Generated by Django 5.2.5 on 2026-06-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_journalentry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='gratitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tomorrow_goal',
            field=models.TextField(blank=True),
        ),
    ]
