# Generated by Django 5.2.5 on 2026-06-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalentry_gratitude_journalentry_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
