# Generated by Django 5.2.5 on 2026-06-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journalentry_is_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
