# Generated by Django 5.2.5 on 2026-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_rename_is_favourite_journalentry_is_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 Happy'), ('calm', '😌 Calm'), ('neutral', '😐 Neutral'), ('sad', '😞 Sad'), ('angry', '😤angry'), ('excited', '🤩 Excited'), ('tired', '😴 Tired')], default='neutral', max_length=20),
        ),
    ]
