# Generated by Django 5.2.5 on 2026-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_journalentry_options_journalentry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='memory_song',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 Happy'), ('calm', '😌 Calm'), ('neutral', '😐 Neutral'), ('sad', '😢 Sad'), ('angry', '😤angry'), ('excited', '🤩 Excited'), ('tired', '😴 Tired')], default='neutral', max_length=20),
        ),
    ]
