# Generated by Django 5.2.5 on 2026-07-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_journalentry_memory_song_alter_journalentry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='weather',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
